# coding: utf-8

"""
    gaqqie device API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: tknsryk@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Job(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'provider_name': 'str',
        'device_name': 'str',
        'create_time': 'str',
        'instructions': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'provider_name': 'provider_name',
        'device_name': 'device_name',
        'create_time': 'create_time',
        'instructions': 'instructions'
    }

    def __init__(self, id=None, name=None, provider_name=None, device_name=None, create_time=None, instructions=None):  # noqa: E501
        """Job - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._provider_name = None
        self._device_name = None
        self._create_time = None
        self._instructions = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if provider_name is not None:
            self.provider_name = provider_name
        if device_name is not None:
            self.device_name = device_name
        if create_time is not None:
            self.create_time = create_time
        if instructions is not None:
            self.instructions = instructions

    @property
    def id(self):
        """Gets the id of this Job.  # noqa: E501

        a unique id of job  # noqa: E501

        :return: The id of this Job.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Job.

        a unique id of job  # noqa: E501

        :param id: The id of this Job.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Job.  # noqa: E501


        :return: The name of this Job.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Job.


        :param name: The name of this Job.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def provider_name(self):
        """Gets the provider_name of this Job.  # noqa: E501


        :return: The provider_name of this Job.  # noqa: E501
        :rtype: str
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name):
        """Sets the provider_name of this Job.


        :param provider_name: The provider_name of this Job.  # noqa: E501
        :type: str
        """

        self._provider_name = provider_name

    @property
    def device_name(self):
        """Gets the device_name of this Job.  # noqa: E501


        :return: The device_name of this Job.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """Sets the device_name of this Job.


        :param device_name: The device_name of this Job.  # noqa: E501
        :type: str
        """

        self._device_name = device_name

    @property
    def create_time(self):
        """Gets the create_time of this Job.  # noqa: E501


        :return: The create_time of this Job.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this Job.


        :param create_time: The create_time of this Job.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def instructions(self):
        """Gets the instructions of this Job.  # noqa: E501


        :return: The instructions of this Job.  # noqa: E501
        :rtype: str
        """
        return self._instructions

    @instructions.setter
    def instructions(self, instructions):
        """Sets the instructions of this Job.


        :param instructions: The instructions of this Job.  # noqa: E501
        :type: str
        """

        self._instructions = instructions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Job, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Job):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
